[package]
name = "pie-crust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = "0.7.2"
glam = "0.22.0"
lerp = "0.4.0"
ordered-float = "3.4.0"
rayon = "1.6.1"
